### ISSUE TITLE
Creating product associations generates a modal that goes outside of browser view

### ISSUE THREAD

**Issue by Repox** [getcandy/hub#12]
[Example](https://i.imgur.com/TMg8rU6.png).

Don't mind the missing product names, that's a result of testing another branch.

**Comment by alecritson** [comment]
Woah, okay yeah this needs looking at

**Comment by alecritson** [comment]
In the latest version this should open out in a panel rather than a modal, is this all good?

**Comment by alecritson** [comment]
This should be fixed in [`0.12.0`](https://github.com/getcandy/hub/releases/tag/0.12.0). If the issue persists after updating, please re open the issue.

For a guide on how to update to `0.12` from `0.11` see links below:

[Upgrading the Hub](https://docs.getcandy.io/hub/prologue/upgrading.html#_0-12)
[Upgrading the API](https://docs.getcandy.io/api/prologue/upgrading.html)
