### ISSUE TITLE
Cannot read property 'company_name' of null

### ISSUE THREAD

**Issue by naifmhd** [getcandy/hub#24]
Page
users

Steps to reproduce:

**Comment by alecritson** [comment]
Thanks @naifmhd this will be fixed in the next release :)

**Comment by alecritson** [comment]
This should be fixed in [`0.12.0`](https://github.com/getcandy/hub/releases/tag/0.12.0). If the issue persists after updating, please re open the issue.

For a guide on how to update to `0.12` from `0.11` see links below:

[Upgrading the Hub](https://docs.getcandy.io/hub/prologue/upgrading.html#_0-12)
[Upgrading the API](https://docs.getcandy.io/api/prologue/upgrading.html)
