### ISSUE TITLE
Cannot read property 'label' of undefined

### ISSUE THREAD

**Issue by jobnomade** [getcandy/hub#25]
Affected version:  `"version": "0.11.5"`

**Page**
settings-attributes-id

**Steps to reproduce:**
1. Create a new attribute
2. Pick "Multiselect" or "Select" type
3. And the error appears

<img width="1030" alt="Screenshot 2021-02-01 at 23 50 56" src="https://user-images.githubusercontent.com/466037/106528085-7569f280-64e8-11eb-8112-2aa90e7c4bef.png">

**Comment by alecritson** [comment]
Thanks @jobnomade this should be fixed in the next release :)

**Comment by alecritson** [comment]
This should be fixed in [`0.12.0`](https://github.com/getcandy/hub/releases/tag/0.12.0). If the issue persists after updating, please re open the issue.

For a guide on how to update to `0.12` from `0.11` see links below:

[Upgrading the Hub](https://docs.getcandy.io/hub/prologue/upgrading.html#_0-12)
[Upgrading the API](https://docs.getcandy.io/api/prologue/upgrading.html)
