### ISSUE TITLE
Request failed with status code 422

### ISSUE THREAD

**Issue by daolvcntt** [getcandy/hub#29]
Page
products.edit.availability

Steps to reproduce:

**Comment by alecritson** [comment]
Do you have any more info on this one? What was the response on the 422?

**Comment by alecritson** [comment]
This should be fixed in [`0.12.0`](https://github.com/getcandy/hub/releases/tag/0.12.0). If the issue persists after updating, please re open the issue.

For a guide on how to update to `0.12` from `0.11` see links below:

[Upgrading the Hub](https://docs.getcandy.io/hub/prologue/upgrading.html#_0-12)
[Upgrading the API](https://docs.getcandy.io/api/prologue/upgrading.html)
