### ISSUE TITLE
Catalogue Manager ignores data when reloading field data

### ISSUE THREAD

**Issue by Repox** [getcandy/hub#31]
When using `/catalogue-manager/products/{product-id}` and updating data, switching tabs ignore updates to fields and overwrites fields with previous values.

https://i.imgur.com/qdM9WwE.mp4

**Comment by alecritson** [comment]
Thanks for reporting! Identified the issue and should be sorted in the next release.

**Comment by alecritson** [comment]
This should be fixed in [`0.12.0`](https://github.com/getcandy/hub/releases/tag/0.12.0). If the issue persists after updating, please re open the issue.

For a guide on how to update to `0.12` from `0.11` see links below:

[Upgrading the Hub](https://docs.getcandy.io/hub/prologue/upgrading.html#_0-12)
[Upgrading the API](https://docs.getcandy.io/api/prologue/upgrading.html)
