### ISSUE TITLE
File upload is quirky

### ISSUE THREAD

**Issue by Repox** [getcandy/hub#32]
When uploading files to a product, files are correctly uploaded to the server, but it seems more like a matter of luck if the media is attached to the product.

https://i.imgur.com/fXxNIgy.mp4

**Comment by alecritson** [comment]
I was working on the product drafting today and identified an issue where assets added to a product weren't being carried across. Requires an update to the API and Hub which hopefully will come soon.

**Comment by alecritson** [comment]
This should be fixed in [`0.12.0`](https://github.com/getcandy/hub/releases/tag/0.12.0). If the issue persists after updating, please re open the issue.

For a guide on how to update to `0.12` from `0.11` see links below:

[Upgrading the Hub](https://docs.getcandy.io/hub/prologue/upgrading.html#_0-12)
[Upgrading the API](https://docs.getcandy.io/api/prologue/upgrading.html)
