### ISSUE TITLE
Bug Edit Product

### ISSUE THREAD

**Issue by daolvcntt** [getcandy/hub#33]
if we edit one product and we press [publish] much information about the product disappears (no more pictures, messy options, or options that disappear, ...)
After update id hash be changed

**Comment by alecritson** [comment]
Thanks for raising this, we're getting a release ready that refactors alot of the way drafting/publishing works. Bear with a little bit and hopefully we can get this sorted.

**Comment by alecritson** [comment]
This should be fixed in [`0.12.0`](https://github.com/getcandy/hub/releases/tag/0.12.0). If the issue persists after updating, please re open the issue.

For a guide on how to update to `0.12` from `0.11` see links below:

[Upgrading the Hub](https://docs.getcandy.io/hub/prologue/upgrading.html#_0-12)
[Upgrading the API](https://docs.getcandy.io/api/prologue/upgrading.html)
