### ISSUE TITLE
Cannot change user password

### ISSUE THREAD

**Issue by johshej** [getcandy/hub#34]
Hi.
When trying to change my user password, I get this

![gc-hub-error-changing-password](https://user-images.githubusercontent.com/4059954/108211944-9f005c00-712d-11eb-9495-7aff89a10f88.png)

The API responds with 
`errors: {password: ["The password confirmation does not match."]}`
+
I checked. The password is right.

**Comment by alecritson** [comment]
Thanks for reporting, I've identified what's happening and should have a fix in the next release :)

**Comment by alecritson** [comment]
This should be fixed in [`0.12.0`](https://github.com/getcandy/hub/releases/tag/0.12.0). If the issue persists after updating, please re open the issue.

For a guide on how to update to `0.12` from `0.11` see links below:

[Upgrading the Hub](https://docs.getcandy.io/hub/prologue/upgrading.html#_0-12)
[Upgrading the API](https://docs.getcandy.io/api/prologue/upgrading.html)
