### ISSUE TITLE
Edit user not showing

### ISSUE THREAD

**Issue by johshej** [getcandy/hub#35]
Clicking a users email on the /users renders an empty page.

Only the email is clickable on the /users page. Maybe let the name or the whole line be clickable as well?

**Comment by alecritson** [comment]
When you say an empty page, do you mean the entire app is blank? Is there anything in the console to indicate what's happening?

Having a single clickable link on a table is a convention throughout the app, but we can certainly take a look at this :)

**Comment by johshej** [comment]
I get a nice response from the API, but the console says:

8278491.js:2 TypeError: Cannot read property 'id' of null
    at a.<anonymous> (9bb97f8.js:1)
    at a.t._render (8278491.js:2)
    at a.r (8278491.js:2)
    at pn.get (8278491.js:2)
    at new pn (8278491.js:2)
    at 8278491.js:2
    at a.xn.$mount (8278491.js:2)
    at a.xn.$mount (8278491.js:2)
    at init (8278491.js:2)
    at n (8278491.js:2)

The page is empty like this:
![image](https://user-images.githubusercontent.com/4059954/108343216-fb21b980-71db-11eb-9bc7-e539c5905677.png)

**Comment by alecritson** [comment]
Just out of interest, does your user record in the db have a customer id? if not could you try adding one and then reloading.

**Comment by johshej** [comment]
No. It works nicely, if I manually connect connect it to a Company in DB.

**Comment by alecritson** [comment]
This should be fixed in [`0.12.0`](https://github.com/getcandy/hub/releases/tag/0.12.0). If the issue persists after updating, please re open the issue.

For a guide on how to update to `0.12` from `0.11` see links below:

[Upgrading the Hub](https://docs.getcandy.io/hub/prologue/upgrading.html#_0-12)
[Upgrading the API](https://docs.getcandy.io/api/prologue/upgrading.html)
