### ISSUE TITLE
context.on is not a function

### ISSUE THREAD

**Issue by cfreak** [getcandy/hub#37]
Page
categories.edit.media

Steps to reproduce:

**Comment by alecritson** [comment]
Thanks for reporting! We're currently having a big QA ready for a `0.12` release which will handle these types of issues :)

**Comment by alecritson** [comment]
This should be fixed in [`0.12.0`](https://github.com/getcandy/hub/releases/tag/0.12.0). If the issue persists after updating, please re open the issue.

For a guide on how to update to `0.12` from `0.11` see links below:

[Upgrading the Hub](https://docs.getcandy.io/hub/prologue/upgrading.html#_0-12)
[Upgrading the API](https://docs.getcandy.io/api/prologue/upgrading.html)
