### ISSUE TITLE
Product Unit Price becomes 0 after focusing & unfocusing field.

### ISSUE THREAD

**Issue by geantas** [getcandy/hub#38]
When editing a product, I selected the **Unit Price** (in order to copy-paste). After I unfocused the input field, price becomes 0.00 & the hub tries to save the product, but fails.

I attach the images of before & after focusing on the **Unit Price** field.

![image](https://user-images.githubusercontent.com/34267171/109012753-a33ef300-76b2-11eb-9862-96796a139519.png)
![image](https://user-images.githubusercontent.com/34267171/109013532-953da200-76b3-11eb-8b11-56b31bdc8909.png)
![image](https://user-images.githubusercontent.com/34267171/109012778-adf98800-76b2-11eb-8951-7425623e6c37.png)

**Comment by alecritson** [comment]
We've managed to identify the issue and will be resolved in `0.12`

**Comment by alecritson** [comment]
This should be fixed in [`0.12.0`](https://github.com/getcandy/hub/releases/tag/0.12.0). If the issue persists after updating, please re open the issue.

For a guide on how to update to `0.12` from `0.11` see links below:

[Upgrading the Hub](https://docs.getcandy.io/hub/prologue/upgrading.html#_0-12)
[Upgrading the API](https://docs.getcandy.io/api/prologue/upgrading.html)
